package de.wwu.pi.app;

import static org.junit.Assert.*;

import javax.inject.Inject;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.Archive;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.EmptyAsset;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import de.wwu.javaee.test.runner.MugglExceptionMatcher;
/**
 * This class has been generated by Muggl for the automated testing of method
 * de.wwu.pi.app.ejb.OrderService.doesOrderExists(int orderId).
 * Test cases have been computed using the symbolic execution of Muggl. Muggl
 * is a tool for the fully automated generation of test cases by analysing a
 * program's byte code. It aims at testing any possible flow through the program's
 * code rather than "guessing" required test cases, as a human would do.
 * Refer to http://www.wi.uni-muenster.de/pi/personal/majchrzak.php for more
 * information or contact the author at tim.majchrzak@wi.uni-muenster.de.
 * 
 * Executing the method main(null) will invoke JUnit (if it is in the class path).
 * The methods for setting up the test and for running the tests have also been
 * annotated.
 * 
 * Important settings for this run:
 * Search algorithm:            iterative deepening depth first
 * Time Limit:                  1 hours
 * Maximum loop cycles to take: 200
 * Maximum instructions before
 * finding a new solution:     infinite
 * Solver:                     de.wwu.muggl.solvers.jacop.JaCoPSolverManager
 * 
 * The total number of solutions found was 2. After deleting redundancy and
 * removing unnecessary solutions, 2 distinct test cases were found.
 * There was no further reduction of test cases.
 * 
 * This file has been generated on Wednesday, 01 March, 2017 15:46.
 * 
 * @author Muggl 1.00 Alpha (unreleased)
 */
@RunWith(Arquillian.class)
public class OrderServiceTest_doesOrderExists0 extends AbstractOrderServiceTest {
	@Inject
	private de.wwu.pi.app.ejb.OrderService testedClass;

	@Deployment
	public static Archive<?> createDeployment() {
		return ShrinkWrap.create(WebArchive.class, "test.war")
			.addClasses(requiredApplicationClasses)
			.addAsResource("META-INF/persistence.xml")
			.addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
	}

	private boolean booleantrue;
	private boolean booleanfalse;

	/**
	 * Set up the unit test by initializing the fields to the desired values.
	 */
	@Before public void setUp() {
		this.booleantrue = true;
		this.booleanfalse = false;
	}
	/**
	 * Run the tests on de.wwu.pi.app.ejb.OrderService.doesOrderExists(int orderId).
	 */
	@Test public void testDoesOrderExists1() throws Exception { 
		// pre-execution required data 
		utx.begin();
		em.joinTransaction();
		// generate object with id: de.wwu.pi.app.entities.CustomerOrder30
		de.wwu.pi.app.entities.CustomerOrder customerOrder1 = new de.wwu.pi.app.entities.CustomerOrder();// object id: de.wwu.pi.app.entities.CustomerOrder30
		em.persist(customerOrder1);
		utx.commit();
		em.clear();

		// generate method arguments
		int arg1 = customerOrder1.getOrderId();
		/** SOLUTION 
		{orderId=de.wwu.muggl.solvers.expressions.AutoGeneratedGetterConstant@9c07232}
		  ***********************************/ 
		assertEquals(this.booleantrue, this.testedClass.doesOrderExists(arg1));
		// check post-execution database state 
		de.wwu.pi.app.entities.CustomerOrder entity31_db = (de.wwu.pi.app.entities.CustomerOrder)em.find(de.wwu.pi.app.entities.CustomerOrder.class, customerOrder1.getOrderId());
		assertNotNull(entity31_db);
		assertEquals(customerOrder1.getOrderId(), entity31_db.getOrderId());
	} 
 
	@Test public void testDoesOrderExists2() throws Exception { 
		// pre-execution required data 
		utx.begin();
		em.joinTransaction();
		utx.commit();
		em.clear();

		// generate method arguments
		int arg1 = 1;
		/** SOLUTION 
		{orderId=1}
		  ***********************************/ 
		assertEquals(this.booleanfalse, this.testedClass.doesOrderExists(arg1));
		// check post-execution database state 
	} 
 
}